version: '2'
services:
    web:
        container_name: rapp-react
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
          - "3000:3000"
        volumes:
          - ./src:/var/www/reactapp/src
          - ./package.json:/var/www/reactapp/package.json
          - ./webpack.config.js:/var/www/reactapp/webpack.config.js
          - ./semantic.json:/var/www/reactapp/semantic.json
    db:
        container_name: rapp-mongodb
        image: mongo
        restart: always
        ports:
          - "27017:27017"